### ISSUE TITLE
Not an Issue, But: Just to Clarify?

### ISSUE THREAD

**Issue by rebeltaz** [fieldOfView/ZOffsetPlugin#10]
If I the z-offset is set to -4.35mm in the marlin firmware; Initial Layer Height is set to 0.3mm in Cura; and I set this z-offset plugin to -0.05mm, this would be the equivalent of setting the marlin firmware z-offset to -4.40mm, right? I have to print PETG 0.05mm closer to the bed for good adhesion and it would be great if I could have this set in a Cura PETG profile so I don't forget to do it when switching from PLA.

**Comment by fieldOfView** [comment]
> right?

I actually don't know 100% what Marlin does, but what you say sounds logical, and the intention of this plugin.

If you want to set a Z Offset per material (ie: in the Materials pane of the preferences), see the Material Settings plugin: https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/. Note that a version of that plugin for Cura 4.4 is currently still in review by Ultimaker.
