### ISSUE TITLE
zoffset setting grey / inactive

### ISSUE THREAD

**Issue by muenznej** [fieldOfView/ZOffsetPlugin#18]
Hello,
since i switched from Cura 4.6 on windows to Cura 4.7.0 on linux
the offset plugin does not work for me anymore. its option is grey

![image](https://user-images.githubusercontent.com/26899110/99983809-a1f8e400-2dac-11eb-8750-e5d933b13b08.png)

_Originally posted by @muenznej in https://github.com/fieldOfView/Cura-ZOffsetPlugin/issues/17#issuecomment-732228054_

**Comment by fieldOfView** [comment]
Thanks for adding the screenshot. The setting is not grey because it is disabled (it isn't), but it is grey because it is not set to be visible by default. Right-click the setting and select "Keep setting visible", and it will no longer be rendered grey if you search for it.

**Comment by muenznej** [comment]
ow, sorry -.-
I had leveling problems and i blamed that option, thanks for poiting it out :+1: 
nice support :)

**Comment by fieldOfView** [comment]
It is always nice to get the blame for something random ;-)

Anyway, thanks for reviving that other issue.

**Comment by muenznej** [comment]
> t is always nice to get the blame for something random ;-)

programmers life :man_shrugging:
