### ISSUE TITLE
Z-Offset incrementing in some situations?

### ISSUE THREAD

**Issue by molodeztom** [fieldOfView/ZOffsetPlugin#19]
Hi, thanks for a really helpful plug-in. 
Printer Ancubic i3 mega s, BL-Touch , Cura 4.8.0, Octoprint
I can adjust the distance nozzle to bed by applying e.g Z-offset -0.1. It works fine as expected. 
When the print finishes and I do the same print again starting from Cura it seems the z-offset is subtracted again. Like Z-offset -0.2.
So the nozzle is closer to the bed. 
It does not happen when the printer is switched off. It does not happen when I do auto bed leveling. 
Is this possible or just my feeling? Can I get the actual z-offset by a marlin command ?

**Comment by fieldOfView** [comment]
Does your start gcode include a G28 home command for the Z axis? If it doesn't, the effect would indeed be incremental.

You can try setting the "Extensive Z Offset Processing" option. This will change all the Z coordinates in the gcode instead of manipulating the coordinate system.

**Comment by akfpv-Nightprowler** [comment]
Hello, 
I‘m using the Plugin on to Printers with MBL. Cura 4.11 and 4.12 and habe the same problem. The second print fails because of bad first layer. G28 is part of the Startcode. I will test the extensive mode.

**Comment by fieldOfView** [comment]
Did you get round to test the "Extensive Z Offset Processing" option?

**Comment by fieldOfView** [comment]
I'm going to assume that using the "Extensive Z Offset Processing" option fixed it.
