### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by jrpmedia** [fieldOfView/ZOffsetPlugin#21]
Sorry to be so obvious but more for those that follow my question too ...

<img width="457" alt="Screenshot 2021-04-21 at 09 08 58" src="https://user-images.githubusercontent.com/14167533/115519618-48281780-a281-11eb-957b-ae3bf4b3a24c.png">

I presume this is the correct location for your Plugins value to be input?

Does my 0.5 value here mean it moves the nozzle Away from the Bed b y 0.5mm?

What is 'Extensive Z Offset Processing' for?
Is this your Plugins setting or CURA's?

**Comment by fieldOfView** [comment]
Settings in Cura have tooltips. These tooltips answer both of your questions.
