### ISSUE TITLE
Printer resets on first print

### ISSUE THREAD

**Issue by ch1z** [fieldOfView/ZOffsetPlugin#24]
I'm using Cura 4.6.1 with Octoprint v1.5.3 on my Ultimaker 2+ and Ender 3 Pro. I noticed that after installing the Z Offset plug-in, every time I begin printing the first time since the printer is turned on, the printers disconnect from Octoprint. This has been going on consistently ever since I installed the plug-in.

**Comment by fieldOfView** [comment]
If standard gcode makes your printer disconnect from OctoPrint, I am sorry to say but there is something very wrong with the firmware (or hardware) of your printer setup. I can't imagine a way this is "my fault".
