### ISSUE TITLE
Z offset under Materials Print Settings Tab?

### ISSUE THREAD

**Issue by Brian-Jackson** [fieldOfView/ZOffsetPlugin#29]
Is it possible to have the Z offset listed under the printer settings in materials?  I have a couple of different materials that I have added with different temperature settings that require a different z offset value.  The material setting make adjust automatically so it would be great to enter the value once and every time the filament is selected the value gets changed.  Not sure if this is possible but it would make things nice.

**Comment by fieldOfView** [comment]
This can already be done if you also install the Material Settings plugin. That plugin allows you to select which settings are available in the Materials preference pane.
