### ISSUE TITLE
Only offsets 1st layer, not others

### ISSUE THREAD

**Issue by jremen** [fieldOfView/ZOffsetPlugin#3]
This plugin only makes Z Offset for first layer only (on the buildplate), not the other layers.
Ie. if original layer height is 0.2 mm and offset is set to 0.2 mm, first layer prints at Z0.4 (correct) but others print like nothing has changed, so its: Z0.4, Z0.6, Z0.8 etc

That means I can't keep a nozzle all the time during print above whole object. Which solves nothing for materials like PETG which likes to be „airprinted“. After some time, usually bigger print, there is so much material on the nozzle that it starts to be clogged and later it will leave huge marks of collected material from nozzle on the print.

So for correct PETG printing I have to recalibrate buildplate manually anyway.

**Comment by fieldOfView** [comment]
Consider this example where layer 1 of a print with a first layer height of 0.25, and a Z Offset value of 0.05 is changed:
```
...
;LAYER:0
M107
G0 F4320 X135.625 Y125.625 Z0.3 ;adjusted by z offset
G92 Z0.25 ;consider this the original z before offset
;TYPE:WALL-INNER
...
```
The G92 Z0.25 means that from then on the printer is made to think the Z position of the head is 0.25, whereas in reality it is at 0.3. This means that when the printer is then instructed to go to Z0.35 (0.1 mm above the first layer, which was originally meant to be 0.25 mm thick), it physically goes to 0.40 mm. IE: every Z value after that G92 line is physically offset by 0.05 mm, until the Z axis is homed again.
