### ISSUE TITLE
ZOffset option not available in per model settings

### ISSUE THREAD

**Issue by jottr** [fieldOfView/ZOffsetPlugin#34]
Plugin version: 3.6.0
Cura version:    5.3.1

Option is available in "Print Settings":

<img width="489" alt="image" src="https://github.com/fieldOfView/Cura-ZOffsetPlugin/assets/2744198/13d45d5f-fa2a-4d49-aebe-3ff44c7565c2">

But not in "Per Model Settings":

<img width="762" alt="image" src="https://github.com/fieldOfView/Cura-ZOffsetPlugin/assets/2744198/871e0fc6-2244-4050-8c9d-cc621fd479c7">

It would be very useful to have z-offset accessible in "Per Model Settings" when calibrating the z-offset for the first layer.

**Comment by fieldOfView** [comment]
This is correct and by design. Having different offsets per model could cause collisions with previously printed parts, risking damage to the printer. I don't think I will be implementing this any time soon.
