### ISSUE TITLE
Not showing in 5.4

### ISSUE THREAD

**Issue by macjoel1991** [fieldOfView/ZOffsetPlugin#36]
It isn't showing up in 5.4.0   I have installed/Uninstalled multiple times from within cura and from the git file and still nothing.

**Comment by fieldOfView** [comment]
Please post a link to your Cura.log file. It can be found via Help -> Show configuration folder.

**Comment by ShaneDelmore** [comment]
Not sure if this will help you @macjoel1991 but I ran into a similar issue and found that the plugin was disabled in the marketplace section, even when I uninstalled and reinstalled it kept setting to disabled.  Once I enabled the plugin and restarted Cura it worked for me.

**Comment by fieldOfView** [comment]
It is all guesswork, unless you post a Cura.log
