### ISSUE TITLE
does not work anymore on latest firmware (5.2) on um3

### ISSUE THREAD

**Issue by atar-axis** [fieldOfView/ZOffsetPlugin#4]
take a look here:
https://community.ultimaker.com/topic/27410-startscript-doesnt-work-anymore-after-last-fw-update/?tab=comments#comment-237522

**Comment by fieldOfView** [comment]
This is a bug in the firmware that I cannot fix from my end.

**Comment by atar-axis** [comment]
that's right, i thought you may would like to offer another way to reach the same goal - by changing increasing every G1/G0 Z value for example :)

**Comment by fieldOfView** [comment]
No, I would rather Ultimaker fix their firmware... :)

**Comment by atar-axis** [comment]
Thank you anyway ;)
