### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by entozoon** [fieldOfView/ZOffsetPlugin#6]
I'm not seeing a Z Offset setting anywhere.
- With Cura 4.0 or 4.3

**Comment by entozoon** [comment]
Oh, my apologies. Didn't realise you have to install within marketplace after copying.

**Comment by fieldOfView** [comment]
>  install within marketplace after copying.

Waht do you mean "after copying"? Just install it from the Marketplace, no "copying" or manual installation necessary.
